dependencies:
  - name: postgresql
    version: "0.7.1"
    repository: "https://gitlab-org.gitlab.io/cluster-integration/helm-stable-archive"
    condition: postgresql.enabled
  - name: redis
    version: "3.8.0"
    repository: https://charts.helm.sh/stable
    condition: redis.enabled  
